### PR TITLE
Fix ocp blance and GITT_loop notebook

### LINKED ISSUE #64: Fix OCPBalance
OCPBalance is currently failing, mostly due to the initial guess and bounds.

### PR DESCRIPTION
**Pull request by muhammedsogut**
# Description

OCP balance had a problem with initial guesses and bounds as well as plotting function. Optimum Initial guesses and bounds requires more discussion but OCP balance problem is fixed by making bounds [-100, 100]. It is working for 'Nelder-Mead' but it does not work for differential evolution for the example. 

Fixes #64 #65

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/paramm-team/pybamm-param/blob/main/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [ ] No style issues: `$ python -m nox -s lint`
- [ ] All tests pass: `$ python -m nox -s unit examples integration`
- [ ] Coverage is complete `$ python -m nox -s coverage`
- [ ] The documentation builds: `$ python -m nox -s sphinx`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by PipGrylls** [comment]
I've fixed a linting error, you may want to install or enable a linter in your IDE. But there is a unit test failing as well. Remember to run `nox` and if required all the individual nox parts if one is failing an preventing the others from running.

`
..............F........./Users/pipgrylls/Code/pybamm-param/.nox/unit-3-11/lib/python3.11/site-packages/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py:563: UserWarning: Q_Li=2.0793 Ah is greater than Q_p=1.9464 Ah.
  warnings.warn(f"Q_Li={Q_Li:.4f} Ah is greater than Q_p={Q_p:.4f} Ah.")
./Users/pipgrylls/Code/pybamm-param/pbparam/optimisation_problems/base_optimisation_problem.py:209: RuntimeWarning: Mean of empty slice
  var: [1 / np.nanmean(self.data[var])] * len(self.data[var])
....................
======================================================================
FAIL: test_setup_objective_function (test_optimisation_problems.test_OCP_balance.TestOCPBalance.test_setup_objective_function)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pipgrylls/Code/pybamm-param/tests/unit/test_optimisation_problems/test_OCP_balance.py", line 52, in test_setup_objective_function
    self.assertEqual(optimisation_problem.bounds, [(-100, 100), (-100, 100)])
AssertionError: Lists differ: [(-100000, 100000), (-100000, 100000)] != [(-100, 100), (-100, 100)]

First differing element 0:
(-100000, 100000)
(-100, 100)

- [(-100000, 100000), (-100000, 100000)]
?       ---   ---          ---   ---

+ [(-100, 100), (-100, 100)]

`

**Review by PipGrylls — APPROVED** [review]
Tests are passing and all looks good (not reviewing the CSV files)

**Comment by PipGrylls** [comment]
@brosaplanella Will leave to you to merge but its all good to go I think

**Comment by brosaplanella** [comment]
I have now checked the notebook and fix a few bugs:
- The gradient of the OCV should be around -1 (see data) so we should multiply by the value from OCP balance (rather than divide).
- I have updated the remaining parameters so they match the cell from data (LGM50).
- At the moment we only fit the discharge part, so I am using the `WeppnerHuggins` model and extracting just the data where current is applied. I have modified the for loop to do that.

@muhammedsogut , can you check my changes make sense and tidy the code (i.e. delete what we do not need, maybe add some comments)?

**Review by brosaplanella — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
