### PR TITLE
Review example notebooks

### PR DESCRIPTION
**Pull request by brosaplanella**
# Description

Review and simplify some example notebooks so they are a good starting point to pbparam.

### CODE REVIEW

**Comment by brosaplanella** [comment]
Still need to give a go at the GITT notebook (probably Monday), but feel free to review these two in the meantime.

**Review by muhammedsogut — APPROVED** [review]
Fixed a typo and it looks nice and informative.

**Comment by brosaplanella** [comment]
Now also worked on the GITT_loop example. @muhammedsogut let me know if you have any comments.

**Review by muhammedsogut — APPROVED** [review]
Looks nice.

**Pull request merged**
