### PR TITLE
Creating SPM_GITT

### PR DESCRIPTION
**Pull request by muhammedsogut**
# Description

This PR is created to provide examples for GITT class. Currently, there's one notebook for Weepier&Huggins model but the user can benefit from a BasicGITT example. 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/paramm-team/pybamm-param/blob/main/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

## Key checklist

- [ ] No style issues: `$ python -m nox -s lint`
- [ ] All tests pass: `$ python -m nox -s unit examples integration`
- [ ] Coverage is complete `$ python -m nox -s coverage`
- [ ] The documentation builds: `$ python -m nox -s sphinx`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by brosaplanella** [comment]
@PipGrylls tests are not running on this branch, but coverage was updated. Can you take a look when you have some time?

**Comment by brosaplanella** [comment]
Is this work in progress or can it be reviewed?

**Comment by muhammedsogut** [comment]
The notebook for GITT diffusivity calculation is ready. It can be reviewed. Please let me know if there something to improve.

**Comment by PipGrylls** [comment]
Before we merge this can I confirm this is an extension of the GITT model with an enhanced example in GITT_loop.ipynb and doesn't require an extension to the testing?

**Comment by muhammedsogut** [comment]
Yes it is an updated version of GITT model and an example for it. I think GITT class might need testing.

**Comment by PipGrylls** [comment]
Okay I am merging loop-gitt into this branch the test written for gitt still passes but if it could merit expanding can you do that and push it to this branch then I will review it all.

**Comment by PipGrylls** [comment]
Infact loop-gitt seems to be redundant @muhammedsogut you are the committer on both gitt-model and loop-gitt. Can I confirm loop-gitt is not needed given this branch exists?

**Comment by muhammedsogut** [comment]
Yes that was created to do things done in this PR but I just used this PR and branch for them. Therefore, you can delete loop-gitt. Thanks.

**Review by PipGrylls — APPROVED** [review]
This seems fine, I've run tests locally and merged in changes from some other branches.
One note is that don't make input data on GH too big and make sure it's unlikely to change. The only data up here should be data required for tests, which this is so this is more of an FYI.

**Comment by muhammedsogut** [comment]
Yes actually we might not need all 24 pulses. We can reduce that number in the next PR if it becomes too heavy.

**Pull request merged**
